### ISSUE TITLE
Copying text from cafe chat to white board pastes html for the chat message

### ISSUE THREAD

**Issue by SethEJensen** [craniumcafe/issue-tracker#213] opened 2017-11-06 19:39 UTC
If a user copies the chat message text from the cafe chat and tries to paste them into a blank white board it shows the html surrounding the chat's text. oddly enough when pasting chat text to other text editors such as note pad the html is not brought over.

**Comment by mikeg0** [comment] 2017-12-21 17:52
![image](https://user-images.githubusercontent.com/1077290/34268184-022c3152-e63d-11e7-859e-6ad7093140e9.png)

**Comment by mikeg0** [comment] 2017-12-27 20:52
duplicate of #237

**Closed by mikeg0** 2017-12-27 20:52 UTC
Labels: issue, low priority, whiteboard project
